apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mwvcdk688-go-gitops
  description: This is GitOps manifest for mwvcdk688-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: mwvcdk688-go
    janus-idp.io/tekton: mwvcdk688-go 
    backstage.io/kubernetes-id: mwvcdk688-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mwvcdk688-go
