apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mwvcdk688-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:85028116100acb071f4698ff90d5b2b8db6fa7ac@sha256:c907e5539994c76dd8f0fd95adf7e9635dcd72d26549020dfbbb4046751ea45f
          name: container-image
